### ISSUE TITLE
Cifras de la Biodiversidad

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#100]
Migrar HTML actual de cifra de la Biodiversidad.

**Comment by javiesgm** [comment]
@jumauricio en directorio del portal general actual no encontré los archivos
¿@danipilze tu sabes dónde los encontramos? si en el nuevo portal general (wordpress) queremos incluir la página actual (http://www.sibcolombia.net/web/sib/cifras), ¿Cómo debemos proceder?
