### ISSUE TITLE
Revisar contenidos sección publicar

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#102]
Revisar todos los contenidos de la sección publica y establecer cuáles son los formularios e hipervínculos que deben ir en cada paso.

http://54.173.197.128/publicar/

**Comment by nestorjal** [comment]
Los enlaces no funcionan, por ejemplo: http://sibcolombia.elasticbeanstalk.com/publicar/que-publicar/#Registros-biologicos

**Comment by jumauricio** [comment]
@nestorjal  Ya están actaulizados los enlances
