### ISSUE TITLE
Título de la Sección "Visibiliza tus datos"

### ISSUE THREAD

**Issue by vdean26** [SIB-Colombia/portal_general_wp#107]

**Comment by vdean26** [comment]
El título de esta sección resulta un poco ambiguo y muchas veces no es interpretado correctamente. Algunos usuarios han pensado que esta sección contiene información acerca de "cómo visibilizar sus datos" (en un portal de datos) en lugar de "Cómo dar visibilidad a sus datos" (a través del proceso de publicación)

**Comment by javiesgm** [comment]
@vdean26 @daiesco @adrisoacha @nestorjal 
Sugiero sustituir Visibiliza tus datos por publica tus datos. 

Cómo lo ven ?
