### ISSUE TITLE
CR-SiB ¿Qué tipo de información se puede publicar?

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#108]
La pregunta tiene una inconsistencia teniendo en cuenta que en el canal CR-SiB no se publica, se reporta.

Cambiar la pregunta del asunto por:
**¿Qué tipo de información se puede reportar?**

URL: http://www.sibcolombia.net/cr-sib-2/

**Comment by javiesgm** [comment]
Hecho!
