### ISSUE TITLE
"Redes y socios" section is missing

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#11]
Design for the "Redes y socios" section is not there.
![screen shot 2016-02-04 at 4 04 42 pm](https://cloud.githubusercontent.com/assets/16709812/12829612/14586090-cb59-11e5-8529-62b2ec8c945e.png)
![screen shot 2016-02-04 at 4 03 28 pm](https://cloud.githubusercontent.com/assets/16709812/12829611/1454f50e-cb59-11e5-9bb1-444929115a57.png)

**Comment by adrisoacha** [comment]
¿Con está sección qué ha sucedido? ¿Cuál es el inconveniente?

**Comment by adrisoacha** [comment]
@suriplanta @jumauricio Por favor hablemos de esta sección, creo que podríamos replantearla, facilitar el trabajo y mejorar su visualización.
