### ISSUE TITLE
"Ayuda" section is not showing at all

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#18]
When tapping or clicking on "Ayuda" nothing is loaded, it's design and implementation is completely missing.
![mockups_portal-14](https://cloud.githubusercontent.com/assets/16709812/12857297/53114248-cc17-11e5-8614-4987c5ddcb7d.jpg)
![mockups_portal-12](https://cloud.githubusercontent.com/assets/16709812/12857296/530b64cc-cc17-11e5-854a-bd40982a038a.jpg)

**Comment by suriplanta** [comment]
This section was supposed to be powered by an external forum (external to WordPress), or with a forum plugin, which was not resolved. If it is going to be linked externally, this menu item can be set to send users to the help forum. If this is not going to be included for now, I recommend either to remove this menu option, or to create a (WordPress) page in the meantime.

**Comment by adrisoacha** [comment]
¿Qué se decidio con esta sección? ¿Se va a conectar Vanilla: https://vanillaforums.org/? ¿Quién estaría a cargo de ese proceso? ¿Qué se necesita? @nestorjal
