### ISSUE TITLE
weird text distribution

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/portal_general_wp#19]
_From @danipilze on February 19, 2016 22:28_

![7efef357-3694-4d12-91bb-e0246707c997](https://cloud.githubusercontent.com/assets/3705866/13190914/6e8eadce-d71d-11e5-8247-abe2a32e3461.jpeg)

_Copied from original issue: SIB-Colombia/cygnus#33_

**Comment by jumauricio** [comment]
With the new terms and conditions interface this test distribution on the mobile version was updated. 

http://52.91.25.109/terms
