### ISSUE TITLE
Home: faltan dos secciones 

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#20]
¿Las dos secciones del home (ver imagen) que tenían (Consultar/Publicar/Comunidad SiB y cifras de publicación) se eliminaron?

![image](https://cloud.githubusercontent.com/assets/16558682/13408356/66786d1a-defb-11e5-91c0-1fefd9ec6683.png)

Creo que es relevante hacerlas visibles, especialmente esa y cifras de publicación. Es de los que más consultan los socios.

Estoy de acuerdo en eliminar del home el mapa de publicadores, siempre que se mantenga el botón de la segunda sección comunidad SiB.

**Comment by javiesgm** [comment]
Revisado y actualizado. 
Aún podría mejorarse la visualización de las cifras de publicación pero se hará más adelante.
