### ISSUE TITLE
Home: la opción inferior de correo electrónico no funciona 

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#22]
En la parte inferior de redes y correo electrónico, cuando se hace click sobre el botón de correo electrónico envía a la parte superior. Si ese logo no va a mostrar nada como un formulario de contacto sugiero quitarlo.

**Comment by daiesco** [comment]
Browser: Chrome
1. Botones demasiados exagerados. Deben ser mas discretos. 

![captura de pantalla 2016-02-29 a las 7 42 14 p m](https://cloud.githubusercontent.com/assets/11927544/13413981/d7995c04-df1c-11e5-9239-1cb1b23cd07a.png)

**Comment by javiesgm** [comment]
Podríamos habilitar un formulario de contacto en vez de la opción "mail to"
Pero tengo unas inquietudes: 

@jumauricio 
1. ¿Cuál será el correo al que llegarán estas notificaciones? 
2. Cuando esté lista la implementación del foro vanilla, ¿Este será el canal de recepción?
