### ISSUE TITLE
Home: opción correo electrónico superior no es funcional

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#23]
La opción superior de correo electrónico, en mi caso lleva a Outlook, cosa que no me parece funcional, tiene otras opciones? sugiero dejar un formulario de contacto que se conecte con el CRM.. o algo así

Pda. es el logo de sobre azul con un +

**Comment by daiesco** [comment]
Mala cosa que se tenga que el mailto me obligue a usar Outlook o Mail para escribir al SiB. Corregir.

![captura de pantalla 2016-02-29 a las 7 51 44 p m](https://cloud.githubusercontent.com/assets/11927544/13414122/24344a5a-df1e-11e5-89f1-79eb084ac00d.png)

Por qué no usar el mecanismo de user voice de la página actual?
![captura de pantalla 2016-02-29 a las 7 58 58 p m](https://cloud.githubusercontent.com/assets/11927544/13415553/bf13fde4-df29-11e5-9aa4-9b9cf3acc8bb.png)

**Comment by jumauricio** [comment]
Inicialmente esto va a quedar con un "mail to" mientras la próxima semana lo vinculamos al User voice.

**Comment by jumauricio** [comment]
Se va a hacer un formulario de contacto por ahora.
