### ISSUE TITLE
Breadcrumb: sugiero revisar diseño

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#24]
La ruta de navegación o Breadcrumb del portal creo que es demasiado grande, podría ser un cambio pequeño, minimizar el tamaño y utilizar un color menos llamativo:

![image](https://cloud.githubusercontent.com/assets/16558682/13411142/95907328-df09-11e5-97bb-dbd78bfc5291.png)

**Comment by daiesco** [comment]
De acuerdo, esto no tiene sentido que sea tan grande. Debe ser mas discreto.

**Comment by javiesgm** [comment]
De acuerdo. 
Teniendo en cuenta los niveles de profundidad hemos decidido eliminar los breadcrumbs.
