### ISSUE TITLE
Actualidad: revisar textos

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#25]
Sugiero cambiar Aportamos al nuevo portal SIAC por algo como "SIAC renueva el acceso a la información ambiental de Colombia" y cambiar la palabra lanzó por presentó o algo así.

En "El SiB Colombia colaboró...." algo como "El SiB Colombia mantiene su participación activa en el SIAC a través de datos e información actualizada sobre la biodiversidad del país"

**Comment by daiesco** [comment]
Eliminar esta noticia. No refleja para nada lo realizado ni por el SIAC ni por el SiB
