### ISSUE TITLE
Home: ¿se mantienen estos accesos dividos?

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#27]
No estoy segura, pero recuerdo que habíamos dicho que íbamos a mantener solo dos URL: www.biodiversidad.co y www.sibcolombia.net. Así que data y maps ya no serían ampliamente visibles...

![image](https://cloud.githubusercontent.com/assets/16558682/13412335/9879783a-df10-11e5-8320-69ab38b19ebe.png)

**Comment by daiesco** [comment]
De acuerdo.

**Comment by javiesgm** [comment]
El nuevo footer no tendrá los accesos según el issue #83 
El acceso a los distintos portales será a través de la sección "Servicios" y a través de la página de inicio.
