### ISSUE TITLE
Home: el botón de la licencia no tiene enlace

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#28]
Regularmente cuando se pone el logo del CC en este contexto es porque conecta con la licencia que fue elegida para el producto (página web), en este caso solo esta el logo, no tienen ningún enlace y no es claro si es CC0 o CC-BY o algo así..

**Comment by daiesco** [comment]
Logo demasiado grande y no tiene sentido si no es funcional.... Cuál es la intención?

**Comment by jumauricio** [comment]
Issue que se soluciona con el número #83
