### ISSUE TITLE
Home: el botón de feedback no está

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#29]
El "botón flotante" de feedback no está en el home. Recuerdo que estaba proyectado. Además que se sugiero pensar como hacerlo más funcional para que las letras no estuvieron acostadas y difucultaran su lectura.

**Comment by daiesco** [comment]
De acuerdo, esta función no se puede perder:

![captura de pantalla 2016-02-29 a las 7 58 49 p m](https://cloud.githubusercontent.com/assets/11927544/13414223/e967aff6-df1e-11e5-830f-cc49aa9dba73.png)

**Comment by javiesgm** [comment]
Esto habría que revisarlo @adrisoacha @daiesco @jumauricio . 
El botón de ayuda será omnipresente en la barra de navegación y la idea es que cualquier consulta se maneje a través del foro "vanilla". 

Sin embargo, planteo las siguientes preguntas: 
Una vez que se implemente el foro: 
1. ¿Este será el canal de recepción de preguntas?
2. ¿Se implementará el CRM? 
3. ¿Actualizamos el servicio de "User voice" de todas formas?

**Comment by jumauricio** [comment]
Por ahora dejemos este ícono con la opción de "mail to". Luego del primer milestone vemos como lo vinculamos con Uservocie.
