### ISSUE TITLE
Home: el menú superior no se mantiene en la navegación

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#30]
También recuerdo que dijimos que esta funcionalidad iba, cuando se hace scroll por la página, el menú superior se mantiene (nosotros, actualidad, servicios, etc...) 
Interesante ver esta página que hace lo mismo pero reduce el tamaño del logo para no sobrecargar: http://contreebute.com/

**Comment by daiesco** [comment]
correcto, esta era una característica básica que debería estar en la nueva página

![captura de pantalla 2016-02-29 a las 8 01 37 p m](https://cloud.githubusercontent.com/assets/11927544/13414274/446e2826-df1f-11e5-97a3-674e8f333b8c.png)

**Comment by jumauricio** [comment]
@suriplanta el menú superior es persistente.

**Comment by suriplanta** [comment]
Debe tenerse presente que en ninguno de los diseños ni mockups se especificó esto. Creo que el menú superior es muy alto para esta función. Sin embargo fue implementado.
