### ISSUE TITLE
Nosotros: dejaría la sección solo con los botones

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#31]
Cuando se hace click sobre nosotros se muestra una foto como la del home que dice qué es el SiB...creo que no es funcional

Dejaría solamente los botones de nuestras cifras, informe de resultados y manual de marca

Siguiendo la línea de como está la sección de Servicios. 

Además nuevamente el botón Ver más no lleva a ningún lugar.

**Comment by daiesco** [comment]
Sección entera no funcional (http://sibcolombia.elasticbeanstalk.com/nosotros/)
Cuál es la diferencia con esta (http://sibcolombia.elasticbeanstalk.com/que-es-el-sib/) que tampoco es funcional?

![captura de pantalla 2016-02-29 a las 8 03 10 p m](https://cloud.githubusercontent.com/assets/11927544/13414306/a2603050-df1f-11e5-84e5-845418af1728.png)
