### ISSUE TITLE
Nosotros >>Gobernanza: faltan contenidos

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#36]
En esta sección debería ir la imagen que se hizo para las infografías del comité directivo sobre la estructura de coordinación del SiB Colombia. 

El gráfico deberá incluir los logos de las instituciones que participan en el comité directivo y técnico. y una imagen que se conecte y muestre que la red de socios son organizaciones académicas, gobierno, empresas y sociedad civil. 

También deberá incluir el resumen de los instrumentos de gobernanza una subsección de ¿Qué significa ser socio del SiB Colombia? con un contenido ojalá no solo texto, de la definición de socio y los tipos de socios.

Es necesaria quitar este texto por ahora y el enlace al documento:
Este documento, que está en constante construcción, fue validado por el Equipo Coordinador, los comités del SiB Colombia y enviado para consulta de los socios previo a su publicación. Consolida la misión, visión, principios, estructura de coordinación, instrumentos y demás aspectos necesarios para un funcionamiento eficiente, claro y colaborativo del SiB Colombia.

Así mismo incluir:
El SiB Colombia es una iniciativa creada con el Decreto 1603 de 1994 como parte del proceso de creación del Sistema Nacional Ambiental (SINA) establecido en la Ley 99 de 1993 y la respuesta a los compromisos adquiridos por el país con la ratificación del Convenio sobre Diversidad Biológica (CDB).  

Es liderado por un Comité Directivo (CD-SiB), el cual está conformado por el Ministerio de Ambiente y Desarrollo Sostenible, los 5 institutos de investigación del SINA (IAvH, INVEMAR, SINCHI, IIAP E IDEAM) y la Universidad Nacional de Colombia. El CD-SiB se apoya en un Comité Técnico (CT-SiB), grupos de trabajo  para temas específicos y por un Equipo Coordinador (EC-SiB), el cual cumple las funciones de secretaría técnica, que acoge e implementa las recomendaciones del CD-SiB.

El SiB Colombia es coordinado por el Instituto Humboldt, quién a través de  procesos colaborativos promueve la participación activa del gobierno, la academia, el sector producto y la sociedad civil para la consolidación de datos e información fiables y oportunos que soportan la toma de decisiones en el país. 

¡El inicio de la implementación del SiB Colombia a partir del año 2000, constituyen el primer resultado del nuevo enfoque de gestión de datos e información en el ámbito nacional!

**Comment by daiesco** [comment]
De acuerdo, esta sección tal cual como está no dice absolutamente nada del esquema de gobernanza del SiB Colombia. No veo el equipo coordinador, no veo el comité técnico, no veo el comité directivo.
