### ISSUE TITLE
Nosotros>>Equipo coordinador: el botón de coordinación no funciona

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#37]
Este botón no filtra como los demás (administración de contenidos, comunicaciones, cooperación, etc...)

![image](https://cloud.githubusercontent.com/assets/16558682/13413453/94a2887a-df18-11e5-8a34-d7d387c48924.png)

**Comment by daiesco** [comment]
Browser: Chrome
1. Este esquema jerárquico no dice nada, por qué en dos líneas?
   ![captura de pantalla 2016-02-29 a las 8 28 53 p m](https://cloud.githubusercontent.com/assets/11927544/13414763/1339685c-df23-11e5-8ac4-d16b8c2253d2.png)
2. El "resumen" al lado del nombre no dice nada... solo ruido. Por qué no pensar en el rol de la persona? Demasiado cargado.
   ![captura de pantalla 2016-02-29 a las 8 29 49 p m](https://cloud.githubusercontent.com/assets/11927544/13414803/5f91d748-df23-11e5-97ce-5a61ccefe850.png)
   Un ejemplo:
   ![captura de pantalla 2016-02-29 a las 8 36 51 p m](https://cloud.githubusercontent.com/assets/11927544/13414903/35bb00c4-df24-11e5-846d-2282fc19a5e2.png)
3. No es opción no contar con esta imagen.
   ![captura de pantalla 2016-02-29 a las 8 29 49 p m](https://cloud.githubusercontent.com/assets/11927544/13414816/83dfcbe6-df23-11e5-9b16-fb55cff368f6.png)
4. Por qué al hacer clic en una línea, me envía a una página de búsqueda? Eso no tiene sentido y debería ser mas amable. Que tiene que ver "categorías" y "archivos"?
   ![captura de pantalla 2016-02-29 a las 8 32 34 p m](https://cloud.githubusercontent.com/assets/11927544/13414839/b588f1b8-df23-11e5-9263-a2bf559bf68a.png)
5. Cuál es la lógica aplicada para el orden en que aparecen los personajes? por lo menos debería tener un sentido temático....
6. Dónde está el rol de la persona?
   ![captura de pantalla 2016-02-29 a las 8 39 04 p m](https://cloud.githubusercontent.com/assets/11927544/13414938/8d6fb760-df24-11e5-8194-f1bae8af7675.png)
7. El "leer mas" no lleve a ningún leer mas... de hecho lleva a un leer menos....
   ![captura de pantalla 2016-02-29 a las 8 40 24 p m](https://cloud.githubusercontent.com/assets/11927544/13414966/c1904d3e-df24-11e5-9c05-fd82d6c39763.png)
8. Tenía entendido que tomar todas las fotos en un mismo día era para guardar un patrón... eso no se ve....

**Comment by jumauricio** [comment]
El issue del filtro ya está reportado, con relación a la visualización esta se va a trabajar en una entrega futura.
