### ISSUE TITLE
Nosotros>>Equipo Coordinador: algunos textos sobran

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#38]
Cuando se filtra por alguna línea del equipo, administración de contenidos por ejemplo el resultado muestra la palabra Archivo (que sobra) y por admin (que creo también sobra)

¿Será necesario dejar la fecha?

![image](https://cloud.githubusercontent.com/assets/16558682/13413519/1d02160e-df19-11e5-9f5e-523d3ee795b5.png)

**Comment by daiesco** [comment]
Totalmente, de hecho cuando hace ese filtro extraño me siento yendo a un blog que no tiene nada que ver con la página anterior.

**Comment by jumauricio** [comment]
@suriplanta Por favor quitemos para todas las entrada y publicaciones las opción de visualizar quien publica,

**Comment by jumauricio** [comment]
@suriplanta Aun hay problemas al mostrar los resultados filtrados por líneas de trabajo.

**Comment by suriplanta** [comment]
Ya se modificaron los filtros.
