### ISSUE TITLE
Nosostros >> Equipo Coordinador: un vista de página intermedia que sobra

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#39]
Cuando se filtra la consulta por una línea, ejemplo Tecnologías de la información, el resultado muestra los nombres y ver más y lleva a una página intermedia (que creo es innecesaria) para luego si mostrar el perfil.

**Comment by jumauricio** [comment]
@suriplanta aun estos filtros no están funcionando. Por favor dejémolo listo.

**Comment by suriplanta** [comment]
Ya se solucionó esto.
