### ISSUE TITLE
Nosotros >> principios y políticas: no hay contenido

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#40]
En esta sección no hay contenido, está un lorem ipsum.

Sugiero:
1. El texto de principios del SiB Colombia del documento de Gobernanza
2. Un texto breve sobre las iniciativas que nos enmarcan: datos abiertos, gobierno abierto, ciencia abierta, acceso libre a los datos e información (Ley 1712 de 2014)
3. Una subsección de políticas: con el documento de acuerdos y términos para datos y términos del catálogo.
4. Una sección de licencias, el contenido de GBIF es: http://www.gbif.org/terms/licences
5. El memorando de entendimiento de GBIF: con un breve contexto del porqué está ahí: http://www.gbif.org/terms/licences/data-sharing  (Este es uno de los textos que sería importante traducir)

**Comment by daiesco** [comment]
![captura de pantalla 2016-02-29 a las 8 52 14 p m](https://cloud.githubusercontent.com/assets/11927544/13415137/68033388-df26-11e5-914b-a43e8000f83b.png)

De acuerdo con lo que propone Karen.
