### ISSUE TITLE
Footer - información incorrecta

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#41]
Browser: Chrome
1. No es "Catálogo de especies", es "Catálogo de la biodiversidad".
2. Definir si se usan mayusculas en la iniciales o no. Se presentan casos de ambas formas.
3. El portal general sobraría no? ya estoy en el portal general.
4. Cuál es la intensión del logo de CC?
5. El logo del SiB debería ser funcional
6. Solo tenemos una sede, por que hablar de una SEDE PRINCIPAL.
![captura de pantalla 2016-02-29 a las 7 41 13 p m](https://cloud.githubusercontent.com/assets/11927544/13413959/9453f5ee-df1c-11e5-9fbb-52bf2f9aec3c.png)

**Comment by javiesgm** [comment]
Revisamos la información del footer y optamos por una versión simplificada referenciada en el issue #83 
pendiente de actualización por @suriplanta
