### ISSUE TITLE
Actualidad: Aportado por admin

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#42]
Browser: Chrome
Sección actualidad
1. Si todas las notas son aportadas por "admin". Para qué mencionarlo?

![captura de pantalla 2016-02-29 a las 7 45 35 p m](https://cloud.githubusercontent.com/assets/11927544/13414019/347fe65e-df1d-11e5-95c7-638232dbc34a.png)

**Comment by jumauricio** [comment]
@suriplanta Por favor quitemos la visualización del publicador, Dejemos solo la fecha. Mil gracias
