### ISSUE TITLE
Nosotros >> Actualidad: ¿esta sección no se despliega el segundo nivel?

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#43]
A diferencia de las secciones del mismo nivel Nosotros, Servicios y Comunidad, Actualidad no se despliega el segundo nivel sino que se ve en la sección derecha ¿Está definido así?

**Comment by jumauricio** [comment]
Si Karencita, acá va de una a las notas o noticias de esta sección. Nos hay necesidad de una menú específico para esta sección.
