### ISSUE TITLE
Nosotros >> Actualidad: ¿la línea del tiempo se va a mantener?

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#44]
En la sección actualidad sería interesante mantener la línea del tiempo:
http://www.sibcolombia.net/web/sib/linea-de-tiempo

**Comment by daiesco** [comment]
1. Totalmente de acuerdo.
2. No entiendo por que dentro de Actualidad, vuelve a existir un cajón de "Categorías" con "Actualidad nuevamente".
3. Las noticias de esta sección está en su mayoría mal enfocadas o erradas. por ejemplo: "Presentamos al Comité Técnico nuestro planes para 2016"... ese no fue el objetivo!
4. No es posible que tenga que mover el scroll 10 veces para ver el preview de las 9 noticias de este sección.
5. Si estas cajas son tan relevantes (lo imagino por si tamaño) por que no son flotantes?
   ![captura de pantalla 2016-02-29 a las 9 03 02 p m](https://cloud.githubusercontent.com/assets/11927544/13415337/e9944c1a-df27-11e5-9714-19778e6c8701.png)

**Comment by jumauricio** [comment]
1. La línea del tiempo no se va a mantener.
2. Para abril se va a cambiar el home a la vista de cuadrícula.
3. Ya se modificaron las categorias de las publicaciones.
