### ISSUE TITLE
Servicios >> Publicar:nombres de las secciones

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#46]
Sugiero que los nombres de las secciones sean:

Registros biológicos 
Listas de chequeo
Fichas de taxones: Información sobre especies
Registros en el CR-SiB: Datos de licencias y permisos

**Comment by daiesco** [comment]
![captura de pantalla 2016-02-29 a las 9 05 21 p m](https://cloud.githubusercontent.com/assets/11927544/13415374/32c9c7de-df28-11e5-8c81-962b80cad97d.png)
1. El catálogo no se llama "biodiversidad.co"
2. Los nombre de esta caja no dicen nada. Por que no llamarlos "explorar registros biológicos" "Explorar cifras sobre biodiversidad", "cómo o qué publicar?".
3. Es mas la sección se debería llamar como "servicios y herramientas".
