### ISSUE TITLE
SiB Colombia > Herramientas SIB

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#54]
1. La caja dice "caja de herramientas", el breadcrumbs dice "Herramientas SIB" y el section-title dice "Herramientas y recursos adicionales".... cuál de todos es?
   ![captura de pantalla 2016-02-29 a las 9 45 12 p m](https://cloud.githubusercontent.com/assets/11927544/13416122/4767744c-df2e-11e5-84af-4de24e2b7ae9.png)
2. Ninguna de estas es una herramienta del SiB Colombia. Además para que unos círculos tan inmensos sin sentido? Para qué URLs logrando hacer hipervinculos con el texto e imágenes?
   ![captura de pantalla 2016-02-29 a las 9 49 34 p m](https://cloud.githubusercontent.com/assets/11927544/13416133/60c63608-df2e-11e5-8015-515b40cc858f.png)
3. Las herramientas deber estar clasificadas por temáticas o funcionalidades.
4. Hay herramientas sin descripción.
5. Si hay "herramientas y recursos adicionales" cuáles son los recursos adicionales?

**Comment by javiesgm** [comment]
@jumauricio, @adrisoacha, @daiesco 
Creo que es conveniente revisar el contenido de la sección y su visualización. 
¿minireunión en el transcurso del día?
