### ISSUE TITLE
SiB Colombia > Servicios

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#55]
No coincide el Box con lo mostrado en esos círculos...
![captura de pantalla 2016-02-29 a las 10 02 04 p m](https://cloud.githubusercontent.com/assets/11927544/13416393/294f6116-df30-11e5-90e0-81618290d81b.png)

**Comment by adrisoacha** [comment]
Para evaluar, los servicios serían en este orden y con su correspondiente acceso (botón):
1. Publicar
2. Biodiversidad.Co
3. Portal de datos
4. Biodiversidad en cifras
5. Cantos de biodiversidad
6. Caja de herramientas
