### ISSUE TITLE
SiB Colombia > Talleres: no hay contenidos

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#60]
No hay contenidos

**Comment by adrisoacha** [comment]
Sugiero que esta sección se llame "Capacitación" 

Irian las siguientes secciones:
1) Talleres: Los contenidos de talleres disponibles en la sección actualidad > talleres de la actual página web.
2) Videos: una sección que enlaza a los videos de talleres que tenemos en You Tube.
4) Un enlace a la caja de herramientas del SiB Colombia
