### ISSUE TITLE
SiB Colombia > Ayuda: no funciona este enlace

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#63]
No funciona el menú, botón o link. Browser: Chrome
![captura de pantalla 2016-02-29 a las 10 13 32 p m](https://cloud.githubusercontent.com/assets/11927544/13416555/bd444ce6-df31-11e5-9b46-33070131fbd3.png)

**Comment by jumauricio** [comment]
Issue duplicado #18
