### ISSUE TITLE
Guía de estructuración y Publicación de Datos: falta la guía

### ISSUE THREAD

**Issue by daiesco** [SIB-Colombia/portal_general_wp#64]
Esta guía no la encuentro en la nueva página: 
http://www.sibcolombia.net/web/sib/guia-de-estructuracion

**Comment by jumauricio** [comment]
We need to re-design this section, which was product of a specific contract from last year. We will take some time to do it, so I would like to know the urgency of this. According to our project we will work on this later on, however if it's needed for next's week launch we can reorganize priorities internally.
