### ISSUE TITLE
Servicios > Publicar: falta la opción ver más

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#69]
Igual con las otras secciones:
![captura de pantalla 2016-02-29 a las 9 25 22 p m](https://cloud.githubusercontent.com/assets/11927544/13415706/fc3bde52-df2a-11e5-8728-15caf9c69f73.png)

**Comment by jumauricio** [comment]
Este error se debía a una actualización del código de la página, no tiene nada que ver con el diseño final. Ya se terminaron las actualizaciones y este menú desapareció.

**Comment by jumauricio** [comment]
Este error se debía a una actualización del código de la página, no tiene nada que ver con el diseño final. Ya se terminaron las actualizaciones y este menú desapareció.
