### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#7]
The site does not have the Breadcrumbs according to original design.
![screen shot 2016-02-04 at 3 28 20 pm](https://cloud.githubusercontent.com/assets/16709812/12828639/f88bf8e0-cb53-11e5-857a-15c63cacbb3f.png)
![screen shot 2016-02-04 at 3 20 59 pm](https://cloud.githubusercontent.com/assets/16709812/12828640/f8930af4-cb53-11e5-95a8-cd6bf6113918.png)
![screen shot 2016-02-04 at 3 20 50 pm](https://cloud.githubusercontent.com/assets/16709812/12828638/f88b2500-cb53-11e5-80e1-55bdb0605c35.png)

**Comment by suriplanta** [comment]
They exist, but they must be properly set up. To do this you must go to the plugins section > Breadcrumb NavXT > Ajustes

There you find all the settings for displaying the breadcrumbs
