### ISSUE TITLE
Servicios > Publicar: cambiar la visualización de las opciones para publicar

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#70]
Esto no lo entiendo... por qué en dos niveles? CR-SiB no se logra para nada. Además CR.SiB son registros biológicos. Se ocupa demasiado espacio con círculos que no dicen nada.
![captura de pantalla 2016-02-29 a las 9 26 39 p m](https://cloud.githubusercontent.com/assets/11927544/13415736/48a6aefc-df2b-11e5-8103-81d6079dc5d2.png)

**Comment by jumauricio** [comment]
Desde los diseños originales está de esta forma. En el trabajo que vamos a realizar en el transcurso del año revisaremos una propuesta para presentar esta información.

**Comment by jumauricio** [comment]
@javiesgm Javi, por favor regálame la bola naranja de CR-SiB en el mismo color que el resto. Gracias
