### ISSUE TITLE
Comunidad: la sección socios y cómo participar no está disponible

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#74]
Donde están los "socios" y "cómo participar"?
![captura de pantalla 2016-02-29 a las 10 08 44 p m](https://cloud.githubusercontent.com/assets/11927544/13416481/1a4d0302-df31-11e5-87ff-a36f284b45b2.png)

**Comment by javiesgm** [comment]
@jumauricio @adrisoacha 
¿Me podrían ayudar con la estructura de este apartado?
El montaje inicial propuesto en los mockups no cumple con las necesidades del apartado. Sería necesario desarrollar una forma de visualización de la sección teniendo en cuenta las necesidades actuales y proyectadas.
