### ISSUE TITLE
Nosotros > ¿Qué es el SiB Colombia?: faltan contenidos

### ISSUE THREAD

**Issue by adrisoacha** [SIB-Colombia/portal_general_wp#77]
Es importante vincular a la sección Informes de resultados:

Informe 2012
Informe 2014
La sección de reporte sib de la actual página web: http://www.sibcolombia.net/web/sib/reportesib

**Comment by jumauricio** [comment]
@javiesgm Javi, por favor revisa en los documentos de Carlitos si está el PDF o el editable del informe 2012 para poder subirlo a la página nueva. Mil gracias
