### ISSUE TITLE
Social Media icons are oversize

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#78]
Browser: Chrome
1. Botones demasiados exagerados. Deben ser mas discretos. 

![captura de pantalla 2016-02-29 a las 7 42 14 p m](https://cloud.githubusercontent.com/assets/11927544/13413981/d7995c04-df1c-11e5-9239-1cb1b23cd07a.png)

**Comment by javiesgm** [comment]
Serán ubicados en el footer según el nuevo montaje descrito en el issue #83
