### ISSUE TITLE
Team member detail is not as designed

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#8]
When clicking on each team member, its detail should not show "equipo cordinador" as a tittle on the "pop-up". Besides margins make look the text disorganized. In the other hand, when accessing to each team member detail its position and department should be shown, but this information can't be fill out from the CMS.
![screen shot 2016-02-04 at 3 35 26 pm](https://cloud.githubusercontent.com/assets/16709812/12828869/0a7011da-cb55-11e5-8b97-5146c95e5e4b.png)
![screen shot 2016-02-04 at 3 30 49 pm](https://cloud.githubusercontent.com/assets/16709812/12828871/0a74f22c-cb55-11e5-86ec-377a87a4991b.png)
![screen shot 2016-02-04 at 3 30 38 pm](https://cloud.githubusercontent.com/assets/16709812/12828870/0a719ce4-cb55-11e5-8eeb-166360aa9b3e.png)

**Comment by suriplanta** [comment]
The updated version should include a custom field called 'profile_position' to include position and department.
