### ISSUE TITLE
Footer - Logo SiB - Problema para cargar SVG desde Amazon S3

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/portal_general_wp#82]
Necesito reemplazar el logo del SiB pero carga. 

![captura de pantalla 2016-03-04 a las 10 31 53 a m](https://cloud.githubusercontent.com/assets/14220404/13531413/70a85920-e1f4-11e5-9779-df2f6d9f0990.png)

**Comment by andresciceri** [comment]
This issue was solved
