### ISSUE TITLE
Contenidos foro SiB Colombia - Vanilla

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#93]
Hacen falta los contenidos que irían en el foro de Vanilla que estamos montando para la página web del SiB  Colombia.

**Comment by nestorjal** [comment]
@jumauricio  @javiesgm 

La plataforma tiene diversas maneras de ser configurada y ahí varía la manera en la que se presentarán los contenidos. Nosotros (AC) como administradores, decidimos los contenidos los subimos nosotros de acuerdo a la manera en la que decidamos mostrar el foro, por lo tanto lo único que necesitamos es el acceso como administradores a la página de Vanila cuando esta esté montada.

Por favor cualquier pregunta estoy metido totalmente con lo de la página.
