### ISSUE TITLE
WordPress caido

### ISSUE THREAD

**Issue by jumauricio** [SIB-Colombia/portal_general_wp#99]
El wordpress está presentando errores graves en el servidor.

**Comment by andresciceri** [comment]
Adjunto la plantilla actual del wordpress que tiene falla para que @suriplanta pueda hacer sus pruebas en su pc local para compararlo con el funcional que tiene.
Estaré pendiente..

[sibsite_30_03_2016.zip](https://github.com/SIB-Colombia/portal_general_wp/files/196804/sibsite_30_03_2016.zip)

**Comment by jumauricio** [comment]
@suriplanta luego del problema con el servidor seguimos sin foorter. Por favor revisemos qué está pasando acá.
